#include "c_emitter.h"

#include <stdio.h>

void ng_c_symbol_for_addr(uint32_t addr, char *out, unsigned out_size) {
    snprintf(out, out_size, "ng_func_%06X", addr & 0xFFFFFFu);
}

int ng_emit_c_skeleton(FILE *out, const NgFunctionDiscovery *discovery) {
    if (!out || !discovery) {
        return 0;
    }

    fprintf(out, "/* Generated by neo-recomp. */\n");
    fprintf(out, "#include <stdint.h>\n");
    fprintf(out, "#include \"ngrecomp/neogeo_runtime.h\"\n\n");

    for (uint32_t i = 0; i < discovery->count; ++i) {
        char symbol[32];
        ng_c_symbol_for_addr(discovery->addrs[i], symbol, (unsigned)sizeof(symbol));
        fprintf(out, "static void %s(void);\n", symbol);
    }

    fprintf(out, "\n");
    fprintf(out, "void ng_generated_call(uint32_t addr) {\n");
    fprintf(out, "    switch (addr & 0x00FFFFFFu) {\n");
    for (uint32_t i = 0; i < discovery->count; ++i) {
        char symbol[32];
        uint32_t addr = discovery->addrs[i] & 0xFFFFFFu;
        ng_c_symbol_for_addr(addr, symbol, (unsigned)sizeof(symbol));
        fprintf(out, "    case 0x%08Xu: %s(); return;\n", addr, symbol);
    }
    fprintf(out, "    default: ng_log_dispatch_miss(addr); return;\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n\n");

    for (uint32_t i = 0; i < discovery->count; ++i) {
        char symbol[32];
        uint32_t addr = discovery->addrs[i] & 0xFFFFFFu;
        ng_c_symbol_for_addr(addr, symbol, (unsigned)sizeof(symbol));
        fprintf(out, "static void %s(void) {\n", symbol);
        fprintf(out, "    /* TODO: emit decoded 68k instructions for $%06X. */\n", addr);
        fprintf(out, "    ng_log_dispatch_miss(0x%08Xu);\n", addr);
        fprintf(out, "}\n\n");
    }

    return ferror(out) == 0;
}
