#include "c_emitter.h"

#include "m68k_decode.h"

#include <stdio.h>

#define NG_EMIT_MAX_INSTRUCTIONS 64u
#define NG_CCR_C 0x0001u
#define NG_CCR_Z 0x0004u
#define NG_CCR_N 0x0008u

void ng_c_symbol_for_addr(uint32_t addr, char *out, unsigned out_size) {
    snprintf(out, out_size, "ng_func_%06X", addr & 0xFFFFFFu);
}

static void ng_c_label_for_addr(uint32_t addr, char *out, unsigned out_size) {
    snprintf(out, out_size, "ng_label_%06X", addr & 0xFFFFFFu);
}

static void emit_header(FILE *out) {
    fprintf(out, "/* Generated by neo-recomp. */\n");
    fprintf(out, "#include <stdint.h>\n");
    fprintf(out, "#include \"ngrecomp/neogeo_runtime.h\"\n\n");
    fprintf(out, "#define NG_CCR_C 0x0001u\n");
    fprintf(out, "#define NG_CCR_Z 0x0004u\n");
    fprintf(out, "#define NG_CCR_N 0x0008u\n\n");
    fprintf(out, "static void ng_set_nz16(uint16_t value) {\n");
    fprintf(out, "    g_ng_m68k.sr = (uint16_t)(g_ng_m68k.sr & 0xFFF0u);\n");
    fprintf(out, "    if (value == 0) g_ng_m68k.sr |= NG_CCR_Z;\n");
    fprintf(out, "    if (value & 0x8000u) g_ng_m68k.sr |= NG_CCR_N;\n");
    fprintf(out, "}\n\n");
    fprintf(out, "static void ng_set_nz8(uint8_t value) {\n");
    fprintf(out, "    g_ng_m68k.sr = (uint16_t)(g_ng_m68k.sr & 0xFFF0u);\n");
    fprintf(out, "    if (value == 0) g_ng_m68k.sr |= NG_CCR_Z;\n");
    fprintf(out, "    if (value & 0x80u) g_ng_m68k.sr |= NG_CCR_N;\n");
    fprintf(out, "}\n\n");
    fprintf(out, "static void ng_set_nz32(uint32_t value) {\n");
    fprintf(out, "    g_ng_m68k.sr = (uint16_t)(g_ng_m68k.sr & 0xFFF0u);\n");
    fprintf(out, "    if (value == 0) g_ng_m68k.sr |= NG_CCR_Z;\n");
    fprintf(out, "    if (value & 0x80000000u) g_ng_m68k.sr |= NG_CCR_N;\n");
    fprintf(out, "}\n\n");
}

static void emit_declarations(FILE *out, const NgFunctionDiscovery *discovery) {
    for (uint32_t i = 0; i < discovery->count; ++i) {
        char symbol[32];
        ng_c_symbol_for_addr(discovery->addrs[i], symbol, (unsigned)sizeof(symbol));
        fprintf(out, "static void %s(void);\n", symbol);
    }
}

static void emit_dispatch(FILE *out, const NgFunctionDiscovery *discovery) {
    fprintf(out, "\n");
    fprintf(out, "void ng_generated_call(uint32_t addr) {\n");
    fprintf(out, "    switch (addr & 0x00FFFFFFu) {\n");
    for (uint32_t i = 0; i < discovery->count; ++i) {
        char symbol[32];
        uint32_t addr = discovery->addrs[i] & 0xFFFFFFu;
        ng_c_symbol_for_addr(addr, symbol, (unsigned)sizeof(symbol));
        fprintf(out, "    case 0x%08Xu: %s(); return;\n", addr, symbol);
    }
    fprintf(out, "    default: ng_log_dispatch_miss(addr); return;\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n\n");
}

static int emit_branch_condition(FILE *out,
                                 const NgM68kInstr *instr,
                                 const char *target_label) {
    if (instr->condition == 6u) {
        fprintf(out, "    if ((g_ng_m68k.sr & NG_CCR_Z) == 0) goto %s;\n",
                target_label);
        return 1;
    }
    if (instr->condition == 4u) {
        fprintf(out, "    if ((g_ng_m68k.sr & NG_CCR_C) == 0) goto %s;\n",
                target_label);
        return 1;
    }
    if (instr->condition == 5u) {
        fprintf(out, "    if ((g_ng_m68k.sr & NG_CCR_C) != 0) goto %s;\n",
                target_label);
        return 1;
    }
    if (instr->condition == 7u) {
        fprintf(out, "    if ((g_ng_m68k.sr & NG_CCR_Z) != 0) goto %s;\n",
                target_label);
        return 1;
    }

    fprintf(out, "    ng_log_dispatch_miss(0x%08Xu);\n", instr->addr & 0x00FFFFFFu);
    fprintf(out, "    return;\n");
    return 0;
}

static int emit_instr(FILE *out, const NgM68kInstr *instr) {
    char target_label[32];

    switch (instr->mnemonic) {
    case NG_M68K_NOP:
        fprintf(out, "    /* NOP */\n");
        return 1;
    case NG_M68K_RTS:
        fprintf(out, "    return;\n");
        return 0;
    case NG_M68K_LEA:
        fprintf(out, "    g_ng_m68k.a[%u] = 0x%08Xu;\n",
                instr->reg, instr->target & 0x00FFFFFFu);
        return 1;
    case NG_M68K_MOVEA:
        if (instr->form == NG_M68K_FORM_PC_INDEX_TO_AREG) {
            fprintf(out,
                    "    g_ng_m68k.a[%u] = ng68k_read32(0x%08Xu + (uint32_t)(int16_t)(g_ng_m68k.d[%u] & 0xFFFFu));\n",
                    instr->reg, instr->target & 0x00FFFFFFu, instr->src_reg);
            return 1;
        }
        break;
    case NG_M68K_MOVEQ:
        fprintf(out, "    g_ng_m68k.d[%u] = 0x%08Xu;\n",
                instr->reg, instr->immediate);
        fprintf(out, "    ng_set_nz32(g_ng_m68k.d[%u]);\n", instr->reg);
        return 1;
    case NG_M68K_MOVE:
        if (instr->form == NG_M68K_FORM_AREG_TO_ABS && instr->size == 4u) {
            fprintf(out, "    ng68k_write32(0x%08Xu, g_ng_m68k.a[%u]);\n",
                    instr->absolute_addr & 0x00FFFFFFu, instr->reg);
            fprintf(out, "    ng_set_nz32(g_ng_m68k.a[%u]);\n", instr->reg);
            return 1;
        }
        if (instr->form == NG_M68K_FORM_IMM_TO_ABS) {
            if (instr->size == 4u) {
                fprintf(out, "    ng68k_write32(0x%08Xu, 0x%08Xu);\n",
                        instr->absolute_addr & 0x00FFFFFFu, instr->immediate);
                fprintf(out, "    ng_set_nz32(0x%08Xu);\n", instr->immediate);
            } else if (instr->size == 1u) {
                fprintf(out, "    ng68k_write8(0x%08Xu, 0x%02Xu);\n",
                        instr->absolute_addr & 0x00FFFFFFu, instr->immediate & 0xFFu);
                fprintf(out, "    ng_set_nz8(0x%02Xu);\n", instr->immediate & 0xFFu);
            } else {
                fprintf(out, "    ng68k_write16(0x%08Xu, 0x%04Xu);\n",
                        instr->absolute_addr & 0x00FFFFFFu, instr->immediate & 0xFFFFu);
                fprintf(out, "    ng_set_nz16(0x%04Xu);\n", instr->immediate & 0xFFFFu);
            }
            return 1;
        }
        if (instr->form == NG_M68K_FORM_ABS_TO_DREG) {
            if (instr->size == 1u) {
                fprintf(out,
                        "    g_ng_m68k.d[%u] = (g_ng_m68k.d[%u] & 0xFFFFFF00u) | ng68k_read8(0x%08Xu);\n",
                        instr->reg, instr->reg, instr->absolute_addr & 0x00FFFFFFu);
                fprintf(out, "    ng_set_nz8((uint8_t)(g_ng_m68k.d[%u] & 0x00FFu));\n",
                        instr->reg);
            } else if (instr->size == 4u) {
                fprintf(out, "    g_ng_m68k.d[%u] = ng68k_read32(0x%08Xu);\n",
                        instr->reg, instr->absolute_addr & 0x00FFFFFFu);
                fprintf(out, "    ng_set_nz32(g_ng_m68k.d[%u]);\n", instr->reg);
            } else {
                fprintf(out,
                        "    g_ng_m68k.d[%u] = (g_ng_m68k.d[%u] & 0xFFFF0000u) | ng68k_read16(0x%08Xu);\n",
                        instr->reg, instr->reg, instr->absolute_addr & 0x00FFFFFFu);
                fprintf(out, "    ng_set_nz16((uint16_t)(g_ng_m68k.d[%u] & 0xFFFFu));\n",
                        instr->reg);
            }
            return 1;
        }
        if (instr->form == NG_M68K_FORM_DREG_TO_ABS && instr->size == 1u) {
            fprintf(out, "    ng68k_write8(0x%08Xu, (uint8_t)(g_ng_m68k.d[%u] & 0x00FFu));\n",
                    instr->absolute_addr & 0x00FFFFFFu, instr->reg);
            fprintf(out, "    ng_set_nz8((uint8_t)(g_ng_m68k.d[%u] & 0x00FFu));\n",
                    instr->reg);
            return 1;
        }
        if (instr->form == NG_M68K_FORM_IMM_TO_DREG) {
            if (instr->size == 1u) {
                fprintf(out,
                        "    g_ng_m68k.d[%u] = (g_ng_m68k.d[%u] & 0xFFFFFF00u) | 0x%02Xu;\n",
                        instr->reg, instr->reg, instr->immediate & 0xFFu);
                fprintf(out, "    ng_set_nz8((uint8_t)(g_ng_m68k.d[%u] & 0x00FFu));\n",
                        instr->reg);
            } else {
                fprintf(out,
                        "    g_ng_m68k.d[%u] = (g_ng_m68k.d[%u] & 0xFFFF0000u) | 0x%04Xu;\n",
                        instr->reg, instr->reg, instr->immediate & 0xFFFFu);
                fprintf(out, "    ng_set_nz16((uint16_t)(g_ng_m68k.d[%u] & 0xFFFFu));\n",
                        instr->reg);
            }
            return 1;
        }
        break;
    case NG_M68K_ADD:
        if (instr->form == NG_M68K_FORM_DREG_TO_DREG && instr->size == 2u) {
            fprintf(out,
                    "    g_ng_m68k.d[%u] = (g_ng_m68k.d[%u] & 0xFFFF0000u) | ((g_ng_m68k.d[%u] + g_ng_m68k.d[%u]) & 0x0000FFFFu);\n",
                    instr->reg, instr->reg, instr->reg, instr->src_reg);
            fprintf(out, "    ng_set_nz16((uint16_t)(g_ng_m68k.d[%u] & 0xFFFFu));\n",
                    instr->reg);
            return 1;
        }
        break;
    case NG_M68K_CLR:
        if (instr->form == NG_M68K_FORM_ABS) {
            if (instr->size == 4u) {
                fprintf(out, "    ng68k_write32(0x%08Xu, 0x00000000u);\n",
                        instr->absolute_addr & 0x00FFFFFFu);
                fprintf(out, "    ng_set_nz32(0);\n");
            } else if (instr->size == 1u) {
                fprintf(out, "    ng68k_write8(0x%08Xu, 0x00u);\n",
                        instr->absolute_addr & 0x00FFFFFFu);
                fprintf(out, "    ng_set_nz8(0);\n");
            } else {
                fprintf(out, "    ng68k_write16(0x%08Xu, 0x0000u);\n",
                        instr->absolute_addr & 0x00FFFFFFu);
                fprintf(out, "    ng_set_nz16(0);\n");
            }
            return 1;
        }
        if (instr->form == NG_M68K_FORM_DREG) {
            if (instr->size == 4u) {
                fprintf(out, "    g_ng_m68k.d[%u] = 0;\n", instr->reg);
                fprintf(out, "    ng_set_nz32(0);\n");
            } else if (instr->size == 1u) {
                fprintf(out, "    g_ng_m68k.d[%u] &= 0xFFFFFF00u;\n", instr->reg);
                fprintf(out, "    ng_set_nz8(0);\n");
            } else {
                fprintf(out, "    g_ng_m68k.d[%u] &= 0xFFFF0000u;\n", instr->reg);
                fprintf(out, "    ng_set_nz16(0);\n");
            }
            return 1;
        }
        break;
    case NG_M68K_TST:
        if (instr->form == NG_M68K_FORM_ABS) {
            if (instr->size == 4u) {
                fprintf(out, "    ng_set_nz32(ng68k_read32(0x%08Xu));\n",
                        instr->absolute_addr & 0x00FFFFFFu);
            } else if (instr->size == 1u) {
                fprintf(out, "    ng_set_nz8(ng68k_read8(0x%08Xu));\n",
                        instr->absolute_addr & 0x00FFFFFFu);
            } else {
                fprintf(out, "    ng_set_nz16(ng68k_read16(0x%08Xu));\n",
                        instr->absolute_addr & 0x00FFFFFFu);
            }
            return 1;
        }
        break;
    case NG_M68K_CMPI:
        if (instr->form == NG_M68K_FORM_IMM_TO_DREG && instr->size == 1u) {
            fprintf(out,
                    "    ng_set_nz8((uint8_t)((g_ng_m68k.d[%u] & 0x00FFu) - 0x%02Xu));\n",
                    instr->reg, instr->immediate & 0xFFu);
            fprintf(out,
                    "    if ((uint8_t)(g_ng_m68k.d[%u] & 0x00FFu) < 0x%02Xu) g_ng_m68k.sr |= NG_CCR_C;\n",
                    instr->reg, instr->immediate & 0xFFu);
            return 1;
        }
        break;
    case NG_M68K_BCLR:
        fprintf(out,
                "    ng68k_write8(0x%08Xu, (uint8_t)(ng68k_read8(0x%08Xu) & (uint8_t)~0x%02Xu));\n",
                instr->absolute_addr & 0x00FFFFFFu,
                instr->absolute_addr & 0x00FFFFFFu,
                (unsigned)(1u << (instr->immediate & 7u)));
        return 1;
    case NG_M68K_ANDI_TO_SR:
        fprintf(out, "    g_ng_m68k.sr &= 0x%04Xu;\n", instr->immediate & 0xFFFFu);
        return 1;
    case NG_M68K_BRA:
        ng_c_label_for_addr(instr->target, target_label, (unsigned)sizeof(target_label));
        fprintf(out, "    goto %s;\n", target_label);
        return 1;
    case NG_M68K_BCC:
        ng_c_label_for_addr(instr->target, target_label, (unsigned)sizeof(target_label));
        return emit_branch_condition(out, instr, target_label);
    case NG_M68K_JSR:
    case NG_M68K_BSR:
        fprintf(out, "    ng_generated_call(0x%08Xu);\n", instr->target & 0x00FFFFFFu);
        return 1;
    case NG_M68K_JMP:
        if (instr->form == NG_M68K_FORM_AREG_INDIRECT) {
            fprintf(out, "    ng_generated_call(g_ng_m68k.a[%u]);\n", instr->reg);
        } else {
            fprintf(out, "    ng_generated_call(0x%08Xu);\n", instr->target & 0x00FFFFFFu);
        }
        fprintf(out, "    return;\n");
        return 0;
    default:
        break;
    }

    fprintf(out, "    ng_log_dispatch_miss(0x%08Xu);\n", instr->addr & 0x00FFFFFFu);
    fprintf(out, "    return;\n");
    return 0;
}

static int addr_in_list(const uint32_t *addrs, uint32_t count, uint32_t addr) {
    for (uint32_t i = 0; i < count; ++i) {
        if ((addrs[i] & 0x00FFFFFFu) == (addr & 0x00FFFFFFu)) {
            return 1;
        }
    }
    return 0;
}

static int instr_has_local_branch_target(const NgM68kInstr *instr) {
    return instr->mnemonic == NG_M68K_BRA || instr->mnemonic == NG_M68K_BCC;
}

static void emit_stub_body(FILE *out, uint32_t addr) {
    fprintf(out, "    /* TODO: emit decoded 68k instructions for $%06X. */\n",
            addr & 0x00FFFFFFu);
    fprintf(out, "    ng_log_dispatch_miss(0x%08Xu);\n", addr & 0x00FFFFFFu);
}

static void emit_function_body(FILE *out, const NgProgramRom *rom, uint32_t start_addr) {
    uint32_t pc = start_addr;
    NgM68kInstr instrs[NG_EMIT_MAX_INSTRUCTIONS];
    uint32_t count = 0;
    uint32_t label_targets[NG_EMIT_MAX_INSTRUCTIONS];
    uint32_t label_count = 0;

    for (uint32_t i = 0; i < NG_EMIT_MAX_INSTRUCTIONS; ++i) {
        NgM68kInstr instr;
        if (!ng_m68k_decode(rom, pc, &instr)) {
            fprintf(out, "    ng_log_dispatch_miss(0x%08Xu);\n", pc & 0x00FFFFFFu);
            fprintf(out, "    return;\n");
            return;
        }

        instrs[count++] = instr;
        if (instr_has_local_branch_target(&instr) &&
            !addr_in_list(label_targets, label_count, instr.target)) {
            label_targets[label_count++] = instr.target;
        }
        if (instr.byte_length == 0 ||
            instr.mnemonic == NG_M68K_JMP ||
            instr.mnemonic == NG_M68K_RTS ||
            instr.mnemonic == NG_M68K_UNKNOWN ||
            instr.mnemonic == NG_M68K_INVALID) {
            break;
        }
        pc += instr.byte_length;
    }

    for (uint32_t i = 0; i < count; ++i) {
        char label[32];
        char text[128];
        if (addr_in_list(label_targets, label_count, instrs[i].addr)) {
            ng_c_label_for_addr(instrs[i].addr, label, (unsigned)sizeof(label));
            fprintf(out, "%s:\n", label);
        }
        ng_m68k_format(&instrs[i], text, (unsigned)sizeof(text));
        fprintf(out, "    /* $%06X: %s */\n", instrs[i].addr & 0x00FFFFFFu, text);
        if (!emit_instr(out, &instrs[i])) {
            return;
        }
    }

    for (uint32_t i = 0; i < label_count; ++i) {
        int emitted = 0;
        for (uint32_t j = 0; j < count; ++j) {
            if ((instrs[j].addr & 0x00FFFFFFu) == (label_targets[i] & 0x00FFFFFFu)) {
                emitted = 1;
                break;
            }
        }
        if (!emitted) {
            char label[32];
            ng_c_label_for_addr(label_targets[i], label, (unsigned)sizeof(label));
            fprintf(out, "%s:\n", label);
            fprintf(out, "    ng_generated_call(0x%08Xu);\n",
                    label_targets[i] & 0x00FFFFFFu);
            fprintf(out, "    return;\n");
        }
    }

    fprintf(out, "    ng_log_dispatch_miss(0x%08Xu);\n", pc & 0x00FFFFFFu);
}

static int emit_functions(FILE *out,
                          const NgProgramRom *rom,
                          const NgFunctionDiscovery *discovery) {
    for (uint32_t i = 0; i < discovery->count; ++i) {
        char symbol[32];
        uint32_t addr = discovery->addrs[i] & 0xFFFFFFu;
        ng_c_symbol_for_addr(addr, symbol, (unsigned)sizeof(symbol));
        fprintf(out, "static void %s(void) {\n", symbol);
        if (rom) {
            emit_function_body(out, rom, addr);
        } else {
            emit_stub_body(out, addr);
        }
        fprintf(out, "}\n\n");
    }

    return ferror(out) == 0;
}

int ng_emit_c_skeleton(FILE *out, const NgFunctionDiscovery *discovery) {
    if (!out || !discovery) {
        return 0;
    }

    emit_header(out);
    emit_declarations(out, discovery);
    emit_dispatch(out, discovery);
    return emit_functions(out, NULL, discovery);
}

int ng_emit_c(FILE *out,
              const NgProgramRom *rom,
              const NgFunctionDiscovery *discovery) {
    if (!out || !rom || !discovery) {
        return 0;
    }

    emit_header(out);
    emit_declarations(out, discovery);
    emit_dispatch(out, discovery);
    return emit_functions(out, rom, discovery);
}
