#include "c_emitter.h"

#include "m68k_decode.h"

#include <stdio.h>

#define NG_EMIT_MAX_INSTRUCTIONS 64u

void ng_c_symbol_for_addr(uint32_t addr, char *out, unsigned out_size) {
    snprintf(out, out_size, "ng_func_%06X", addr & 0xFFFFFFu);
}

static void emit_header(FILE *out) {
    fprintf(out, "/* Generated by neo-recomp. */\n");
    fprintf(out, "#include <stdint.h>\n");
    fprintf(out, "#include \"ngrecomp/neogeo_runtime.h\"\n\n");
}

static void emit_declarations(FILE *out, const NgFunctionDiscovery *discovery) {
    for (uint32_t i = 0; i < discovery->count; ++i) {
        char symbol[32];
        ng_c_symbol_for_addr(discovery->addrs[i], symbol, (unsigned)sizeof(symbol));
        fprintf(out, "static void %s(void);\n", symbol);
    }
}

static void emit_dispatch(FILE *out, const NgFunctionDiscovery *discovery) {
    fprintf(out, "\n");
    fprintf(out, "void ng_generated_call(uint32_t addr) {\n");
    fprintf(out, "    switch (addr & 0x00FFFFFFu) {\n");
    for (uint32_t i = 0; i < discovery->count; ++i) {
        char symbol[32];
        uint32_t addr = discovery->addrs[i] & 0xFFFFFFu;
        ng_c_symbol_for_addr(addr, symbol, (unsigned)sizeof(symbol));
        fprintf(out, "    case 0x%08Xu: %s(); return;\n", addr, symbol);
    }
    fprintf(out, "    default: ng_log_dispatch_miss(addr); return;\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n\n");
}

static int emit_instr(FILE *out, const NgM68kInstr *instr) {
    switch (instr->mnemonic) {
    case NG_M68K_NOP:
        fprintf(out, "    /* NOP */\n");
        return 1;
    case NG_M68K_RTS:
        fprintf(out, "    return;\n");
        return 0;
    case NG_M68K_LEA:
        fprintf(out, "    g_ng_m68k.a[%u] = 0x%08Xu;\n",
                instr->reg, instr->target & 0x00FFFFFFu);
        return 1;
    case NG_M68K_MOVEA:
        if (instr->form == NG_M68K_FORM_PC_INDEX_TO_AREG) {
            fprintf(out,
                    "    g_ng_m68k.a[%u] = ng68k_read32(0x%08Xu + (uint32_t)(int16_t)(g_ng_m68k.d[%u] & 0xFFFFu));\n",
                    instr->reg, instr->target & 0x00FFFFFFu, instr->src_reg);
            return 1;
        }
        break;
    case NG_M68K_MOVEQ:
        fprintf(out, "    g_ng_m68k.d[%u] = 0x%08Xu;\n",
                instr->reg, instr->immediate);
        return 1;
    case NG_M68K_MOVE:
        if (instr->form == NG_M68K_FORM_AREG_TO_ABS && instr->size == 4u) {
            fprintf(out, "    ng68k_write32(0x%08Xu, g_ng_m68k.a[%u]);\n",
                    instr->absolute_addr & 0x00FFFFFFu, instr->reg);
            return 1;
        }
        if (instr->form == NG_M68K_FORM_IMM_TO_ABS) {
            if (instr->size == 4u) {
                fprintf(out, "    ng68k_write32(0x%08Xu, 0x%08Xu);\n",
                        instr->absolute_addr & 0x00FFFFFFu, instr->immediate);
            } else {
                fprintf(out, "    ng68k_write16(0x%08Xu, 0x%04Xu);\n",
                        instr->absolute_addr & 0x00FFFFFFu, instr->immediate & 0xFFFFu);
            }
            return 1;
        }
        if (instr->form == NG_M68K_FORM_ABS_TO_DREG) {
            if (instr->size == 1u) {
                fprintf(out,
                        "    g_ng_m68k.d[%u] = (g_ng_m68k.d[%u] & 0xFFFFFF00u) | ng68k_read8(0x%08Xu);\n",
                        instr->reg, instr->reg, instr->absolute_addr & 0x00FFFFFFu);
            } else if (instr->size == 4u) {
                fprintf(out, "    g_ng_m68k.d[%u] = ng68k_read32(0x%08Xu);\n",
                        instr->reg, instr->absolute_addr & 0x00FFFFFFu);
            } else {
                fprintf(out,
                        "    g_ng_m68k.d[%u] = (g_ng_m68k.d[%u] & 0xFFFF0000u) | ng68k_read16(0x%08Xu);\n",
                        instr->reg, instr->reg, instr->absolute_addr & 0x00FFFFFFu);
            }
            return 1;
        }
        if (instr->form == NG_M68K_FORM_IMM_TO_DREG) {
            fprintf(out,
                    "    g_ng_m68k.d[%u] = (g_ng_m68k.d[%u] & 0xFFFF0000u) | 0x%04Xu;\n",
                    instr->reg, instr->reg, instr->immediate & 0xFFFFu);
            return 1;
        }
        break;
    case NG_M68K_ADD:
        if (instr->form == NG_M68K_FORM_DREG_TO_DREG && instr->size == 2u) {
            fprintf(out,
                    "    g_ng_m68k.d[%u] = (g_ng_m68k.d[%u] & 0xFFFF0000u) | ((g_ng_m68k.d[%u] + g_ng_m68k.d[%u]) & 0x0000FFFFu);\n",
                    instr->reg, instr->reg, instr->reg, instr->src_reg);
            return 1;
        }
        break;
    case NG_M68K_CLR:
        if (instr->form == NG_M68K_FORM_ABS && instr->size == 2u) {
            fprintf(out, "    ng68k_write16(0x%08Xu, 0x0000u);\n",
                    instr->absolute_addr & 0x00FFFFFFu);
            return 1;
        }
        break;
    case NG_M68K_BCLR:
        fprintf(out,
                "    ng68k_write8(0x%08Xu, (uint8_t)(ng68k_read8(0x%08Xu) & (uint8_t)~0x%02Xu));\n",
                instr->absolute_addr & 0x00FFFFFFu,
                instr->absolute_addr & 0x00FFFFFFu,
                (unsigned)(1u << (instr->immediate & 7u)));
        return 1;
    case NG_M68K_ANDI_TO_SR:
        fprintf(out, "    g_ng_m68k.sr &= 0x%04Xu;\n", instr->immediate & 0xFFFFu);
        return 1;
    case NG_M68K_JSR:
    case NG_M68K_BSR:
        fprintf(out, "    ng_generated_call(0x%08Xu);\n", instr->target & 0x00FFFFFFu);
        return 1;
    case NG_M68K_JMP:
        if (instr->form == NG_M68K_FORM_AREG_INDIRECT) {
            fprintf(out, "    ng_generated_call(g_ng_m68k.a[%u]);\n", instr->reg);
        } else {
            fprintf(out, "    ng_generated_call(0x%08Xu);\n", instr->target & 0x00FFFFFFu);
        }
        fprintf(out, "    return;\n");
        return 0;
    default:
        break;
    }

    fprintf(out, "    ng_log_dispatch_miss(0x%08Xu);\n", instr->addr & 0x00FFFFFFu);
    fprintf(out, "    return;\n");
    return 0;
}

static void emit_stub_body(FILE *out, uint32_t addr) {
    fprintf(out, "    /* TODO: emit decoded 68k instructions for $%06X. */\n",
            addr & 0x00FFFFFFu);
    fprintf(out, "    ng_log_dispatch_miss(0x%08Xu);\n", addr & 0x00FFFFFFu);
}

static void emit_function_body(FILE *out, const NgProgramRom *rom, uint32_t start_addr) {
    uint32_t pc = start_addr;
    for (uint32_t i = 0; i < NG_EMIT_MAX_INSTRUCTIONS; ++i) {
        NgM68kInstr instr;
        char text[128];
        if (!ng_m68k_decode(rom, pc, &instr)) {
            fprintf(out, "    ng_log_dispatch_miss(0x%08Xu);\n", pc & 0x00FFFFFFu);
            fprintf(out, "    return;\n");
            return;
        }

        ng_m68k_format(&instr, text, (unsigned)sizeof(text));
        fprintf(out, "    /* $%06X: %s */\n", pc & 0x00FFFFFFu, text);
        if (!emit_instr(out, &instr)) {
            return;
        }
        if (instr.byte_length == 0) {
            fprintf(out, "    return;\n");
            return;
        }
        pc += instr.byte_length;
    }

    fprintf(out, "    ng_log_dispatch_miss(0x%08Xu);\n", pc & 0x00FFFFFFu);
}

static int emit_functions(FILE *out,
                          const NgProgramRom *rom,
                          const NgFunctionDiscovery *discovery) {
    for (uint32_t i = 0; i < discovery->count; ++i) {
        char symbol[32];
        uint32_t addr = discovery->addrs[i] & 0xFFFFFFu;
        ng_c_symbol_for_addr(addr, symbol, (unsigned)sizeof(symbol));
        fprintf(out, "static void %s(void) {\n", symbol);
        if (rom) {
            emit_function_body(out, rom, addr);
        } else {
            emit_stub_body(out, addr);
        }
        fprintf(out, "}\n\n");
    }

    return ferror(out) == 0;
}

int ng_emit_c_skeleton(FILE *out, const NgFunctionDiscovery *discovery) {
    if (!out || !discovery) {
        return 0;
    }

    emit_header(out);
    emit_declarations(out, discovery);
    emit_dispatch(out, discovery);
    return emit_functions(out, NULL, discovery);
}

int ng_emit_c(FILE *out,
              const NgProgramRom *rom,
              const NgFunctionDiscovery *discovery) {
    if (!out || !rom || !discovery) {
        return 0;
    }

    emit_header(out);
    emit_declarations(out, discovery);
    emit_dispatch(out, discovery);
    return emit_functions(out, rom, discovery);
}
