#!/usr/bin/env python3
"""Capture a MAME debugger PC trace for later trace_pc_residual.py analysis."""

from __future__ import annotations

import argparse
import os
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path


def mame_quote(path: Path) -> str:
    text = str(path)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def format_seconds(value: float) -> str:
    if value == int(value):
        return str(int(value))
    return f"{value:.3f}".rstrip("0").rstrip(".")


def write_debug_script(path: Path, trace_output: Path, cpu: str, loops: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    trace_args = [mame_quote(trace_output)]
    if cpu:
        trace_args.append(cpu)
    if loops:
        if not cpu:
            trace_args.append("")
        trace_args.append(loops)

    with path.open("w") as out:
        out.write("# Auto-generated by scripts/mame_trace_capture.py\n")
        out.write(f"trace {','.join(trace_args)}\n")
        out.write("go\n")


def build_command(args: argparse.Namespace, script_path: Path) -> list[str]:
    cmd = [args.mame]
    if args.system:
        cmd.append(args.system)
    if args.software:
        cmd.append(args.software)
    if args.cart:
        cmd.extend(["-cart", str(args.cart)])
    if args.rompath:
        cmd.extend(["-rompath", str(args.rompath)])
    if args.nothrottle:
        cmd.append("-nothrottle")
    if args.video:
        cmd.extend(["-video", args.video])
    if args.sound:
        cmd.extend(["-sound", args.sound])
    if args.seconds > 0:
        cmd.extend(["-seconds_to_run", format_seconds(args.seconds)])
    cmd.extend(["-debug", "-debugscript", str(script_path)])
    cmd.extend(args.mame_args)
    return cmd


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run MAME with a debugger trace command and write a PC trace. "
            "Feed the result to scripts/trace_pc_residual.py."
        ),
    )
    parser.add_argument("--mame", default=os.environ.get("MAME", "mame"),
                        help="MAME executable, default: $MAME or mame")
    parser.add_argument("--system", default="neogeo",
                        help="MAME system or driver name, default: neogeo")
    parser.add_argument("--software",
                        help="Optional software or romset name, for example mslug")
    parser.add_argument("--cart", type=Path,
                        help="Optional cart path for systems that accept -cart")
    parser.add_argument("--rompath", type=Path,
                        help="Optional MAME ROM path")
    parser.add_argument("--seconds", type=float, default=10.0,
                        help="Seconds to run before MAME exits, default: 10")
    parser.add_argument("--trace-output", required=True, type=Path,
                        help="Trace text file to write")
    parser.add_argument("--debugscript-output", type=Path,
                        help="Keep the generated debugger script at this path")
    parser.add_argument("--cpu", default="maincpu",
                        help="MAME CPU tag to trace, default: maincpu")
    parser.add_argument("--loops", choices=("detectloops", "noloops"),
                        default="noloops",
                        help="MAME trace loop handling, default: noloops")
    parser.add_argument("--nothrottle", action="store_true",
                        help="Pass -nothrottle to MAME")
    parser.add_argument("--video", default="none",
                        help="MAME -video backend, default: none")
    parser.add_argument("--sound", default="none",
                        help="MAME -sound backend, default: none")
    parser.add_argument("--dry-run", action="store_true",
                        help="Write or print the debugger script and command without running MAME")
    parser.add_argument("mame_args", nargs=argparse.REMAINDER,
                        help="Extra MAME arguments after --")
    args = parser.parse_args(argv)
    if args.mame_args and args.mame_args[0] == "--":
        args.mame_args = args.mame_args[1:]
    if args.seconds < 0:
        parser.error("--seconds must be non-negative")
    if not args.software and not args.cart:
        parser.error("provide --software ROMSET or --cart PATH")
    return args


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    args.trace_output.parent.mkdir(parents=True, exist_ok=True)

    if args.debugscript_output:
        script_path = args.debugscript_output
        write_debug_script(script_path,
                           args.trace_output.resolve(),
                           args.cpu,
                           args.loops)
        keep_script = True
    else:
        tmp = tempfile.NamedTemporaryFile("w", suffix=".mame", delete=False)
        script_path = Path(tmp.name)
        tmp.close()
        write_debug_script(script_path,
                           args.trace_output.resolve(),
                           args.cpu,
                           args.loops)
        keep_script = False

    cmd = build_command(args, script_path)
    if args.dry_run:
        print("debugger script:", script_path)
        print(script_path.read_text(), end="")
        print("command:", shlex.join(cmd))
        if not keep_script:
            script_path.unlink(missing_ok=True)
        return 0

    try:
        result = subprocess.run(cmd, check=False)
    finally:
        if not keep_script:
            script_path.unlink(missing_ok=True)

    if result.returncode != 0:
        return result.returncode
    if not args.trace_output.exists():
        print(f"MAME exited successfully but did not create {args.trace_output}",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
